name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Install Hugo
        run: make install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        env:
          CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: ./scripts/deploy.sh
